project:
  type: book
  output-dir: _book

book:
  title: "ggplot2: Elegant Graphics for Data Analysis (3e)"
  reader-mode: true

  page-footer:
    left: |
      ggplot2: Elegant Graphics for Data Analysis (3e) was written by
      Hadley Wickham, Danielle Navarro, and Thomas Lin Pedersen.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://ggplot2-book.org/
  repo-url: https://github.com/hadley/ggplot2-book/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.Rmd

    - preface-3e.Rmd
    - preface-2e.Rmd

    - part: Getting Started
      chapters:
        - introduction.Rmd
        - getting-started.Rmd

    - part: toolbox.Rmd
      chapters:
        - individual-geoms.Rmd
        - collective-geoms.Rmd
        - statistical-summaries.Rmd
        - maps.Rmd
        - networks.Rmd
        - annotations.Rmd
        - arranging-plots.Rmd

    - part: scales.Rmd
      chapters:
        - scales-position.Rmd
        - scales-colour.Rmd
        - scales-other.Rmd

    - part: mastery.Rmd
      chapters:
        - layers.Rmd
        - scales-guides.Rmd
        - coord.Rmd
        - facet.Rmd
        - themes.Rmd

    - part: extending.Rmd
      chapters:
        - programming.Rmd
        - internals.Rmd
        - extensions.Rmd
        - ext-springs.Rmd

    - references.Rmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
    code-link: true

    author-meta: "Hadley Wickham, Danielle Navarro, and Thomas Lin Pedersen"
    include-in-header: "ga_script.html"
    callout-appearance: simple

editor: visual

